//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2Documentation.Samples.Extensions.InlineFunctions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2Documentation.Samples.Extensions.InlineFunctions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Web Services.
        /// </summary>
        internal static string ExcelCategory {
            get {
                return ResourceManager.GetString("ExcelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function to return a cell value from an Excel workbook.
        /// </summary>
        internal static string GetCellFunctionDescription {
            get {
                return ResourceManager.GetString("GetCellFunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cell.
        /// </summary>
        internal static string GetCellFunctionName {
            get {
                return ResourceManager.GetString("GetCellFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to Excel workbook.
        /// </summary>
        internal static string GetCellFunctionParm1Description {
            get {
                return ResourceManager.GetString("GetCellFunctionParm1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook URL.
        /// </summary>
        internal static string GetCellFunctionParm1Name {
            get {
                return ResourceManager.GetString("GetCellFunctionParm1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet to use in workbook.
        /// </summary>
        internal static string GetCellFunctionParm2Description {
            get {
                return ResourceManager.GetString("GetCellFunctionParm2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        internal static string GetCellFunctionParm2Name {
            get {
                return ResourceManager.GetString("GetCellFunctionParm2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return cell in ColumnRow format.
        /// </summary>
        internal static string GetCellFunctionParm3Description {
            get {
                return ResourceManager.GetString("GetCellFunctionParm3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Cell.
        /// </summary>
        internal static string GetCellFunctionParm3Name {
            get {
                return ResourceManager.GetString("GetCellFunctionParm3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function to set a cell, calculate and return a cell value from an Excel workbook.
        /// </summary>
        internal static string GetCellWithInputFunctionDescription {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cell With Input.
        /// </summary>
        internal static string GetCellWithInputFunctionName {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to Excel workbook.
        /// </summary>
        internal static string GetCellWithInputFunctionParm1Description {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook URL.
        /// </summary>
        internal static string GetCellWithInputFunctionParm1Name {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet to use in workbook.
        /// </summary>
        internal static string GetCellWithInputFunctionParm2Description {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        internal static string GetCellWithInputFunctionParm2Name {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cell in ColumnRow format.
        /// </summary>
        internal static string GetCellWithInputFunctionParm3Description {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Cell.
        /// </summary>
        internal static string GetCellWithInputFunctionParm3Name {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value.
        /// </summary>
        internal static string GetCellWithInputFunctionParm4Description {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Value.
        /// </summary>
        internal static string GetCellWithInputFunctionParm4Name {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return cell in ColumnRow format.
        /// </summary>
        internal static string GetCellWithInputFunctionParm5Description {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Cell.
        /// </summary>
        internal static string GetCellWithInputFunctionParm5Name {
            get {
                return ResourceManager.GetString("GetCellWithInputFunctionParm5Name", resourceCulture);
            }
        }
    }
}
